name:                asif
version:             3.1.0
github:              "packetloop/asif"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/packetloop/asif#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base >= 4.7 && < 5
- attoparsec
- binary
- bytestring
- conduit
- conduit-combinators
- conduit-extra
- containers
- cpu
- either
- exceptions
- generic-lens
- hw-bits
- hw-ip
- hw-prim
- iproute
- lens
- network
- old-locale
- resourcet
- temporary-resourcet
- text
- thyme
- vector

library:
  source-dirs: src
  exposed-modules:
    - Arbor.File.Format.Asif
    - Arbor.File.Format.Asif.ByIndex
    - Arbor.File.Format.Asif.ByteString
    - Arbor.File.Format.Asif.ByteString.Builder
    - Arbor.File.Format.Asif.ByteString.Lazy
    - Arbor.File.Format.Asif.Data.Ip
    - Arbor.File.Format.Asif.Data.Read
    - Arbor.File.Format.Asif.Extract
    - Arbor.File.Format.Asif.Format
    - Arbor.File.Format.Asif.Get
    - Arbor.File.Format.Asif.IO
    - Arbor.File.Format.Asif.Lookup
    - Arbor.File.Format.Asif.Segment
    - Arbor.File.Format.Asif.Type
    - Arbor.File.Format.Asif.Whatever
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  asif:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -O2
    - -msse4.2
    dependencies:
    - asif
    - directory
    - optparse-applicative

tests:
  asif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asif
    - hspec
    - hedgehog
    - hw-hspec-hedgehog
