name:                asif
version:             1.0.0
github:              "packetloop/asif"
license:             MIT
category:            Services
author:              Tyler Durden
maintainer:          tyler.durden@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/packetloop/asif#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base >= 4.7 && < 5
- attoparsec
- binary
- bytestring
- conduit
- conduit-combinators
- containers
- either
- exceptions
- lens
- vector

library:
  source-dirs: src
  exposed-modules:
    - Arbor.File.Format.Asif
    - Arbor.File.Format.Asif.IO
    - Arbor.File.Format.Asif.ByteString.Builder

tests:
  asif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asif
    - arbor-ip
    - hspec
    - hedgehog
    - hw-hspec-hedgehog
