resolver: lts-11.17

packages:
- .
- location:
    git: git@github.com:packetloop/arbor-ip.git
    commit: 9cea5e3c5e3eeaf767f97749b127a7495604f845
  extra-dep: true

extra-deps:
- hw-fingertree-strict-0.1.0.3
- hw-hspec-hedgehog-0.1.0.4
- lazy-csv-0.5.1
- temporary-resourcet-0.1.0.0
- thyme-0.3.5.5
