resolver: lts-12.10

packages:
- .

extra-deps:
- appar-0.1.7
- hw-fingertree-strict-0.1.0.3
- hw-hspec-hedgehog-0.1.0.4
- hw-ip-2.0.0.0
- lazy-csv-0.5.1
- temporary-resourcet-0.1.0.0
- thyme-0.3.5.5
