version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.6
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.3.1

executors:
  darwin:
    macos:
      xcode: 10.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2
          context: haskell-ci
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.8.2
          executor: haskell/ghc-8_8_2
          context: haskell-ci
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct
          workspace-dir: workspace/ghc-8.8.2
          write-result-workspace: true

      - haskell/build-with-binary-cache:
          name: Darwin
          executor: darwin
          context: haskell-ci
          run-tests: false
          fail-incoherent-builds: false
          write-result-workspace: true
          workspace-dir: workspace/osx
          after-checkout:
            - restore_cache:
                keys:
                  - homebrew-itself-cache
            - run:
                name: Install GHC
                command: |
                  brew update
                  brew install jq md5sha1sum ghc cabal-install
            - save_cache:
                key: homebrew-itself-cache
                # I cache Homebrew itself, not the stuff that is installed with it
                # because brew update takes up to 4 minutes for some reason.
                paths: [/usr/local/Homebrew]

          filters:
            branches:
              only: master

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          requires:
            - GHC 8.2.2
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.2
            - Darwin
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  source ./workspace/ghc-8.8.2/project.env
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./workspace/ghc-8.6.5/dist/ ./${BUILD_EXE_NAME}
                  source ./workspace/osx/project.env
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./workspace/osx/dist/ ./${BUILD_EXE_NAME}
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
